[package]
name = "intermediate_representation"
version = "0.1.0"
edition = "2021"

[dependencies]
enums = { path = "../../ignis_common/enums" }
token = { path = "../token" }

serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
