[package]
name = "ast"
version = "0.1.0"
edition = "2021"

[dependencies]
token = { path = "../token" }
enums = { path = "../../ignis_common/enums" }

serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
