[package]
name = "ast"
version = "0.1.0"
edition = "2021"

[dependencies]
lexer = { path = "../lexer" }
enums = { path = "../enums" }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
