[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
enums = { path = "../../ignis_common/enums" }
token = { path = "../../ignis_data_struct/token" }
ast = { path = "../../ignis_data_struct/ast" }
diagnostic_report  = { path = "../../ignis_data_struct/diagnostic_report" }
